### ISSUE TITLE
Installation is broken on py27

### ISSUE THREAD

**Issue by luckyh** [avocado-framework/inspektor#37]
Got the following error during the ci check of tp-qemu:
```
Collecting cmd2>=0.6.7 (from cliff->inspektor==0.4.5->-r requirements-travis.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/07/4a/f8c16175fa806b9c81f60688411b09a84a23decf774f2cdd5657e43dfe9b/cmd2-0.9.0.post1.tar.gz (136kB)
    100% |████████████████████████████████| 143kB 7.2MB/s 
cmd2 requires Python '>=3.4' but the running Python is 2.7.14
```
I've noticed that someone has already reported bug to cliff, so what we need to do later is to update the requirement to the latest one for py27 once the bug being fixed.

https://bugs.launchpad.net/python-cliff/+bug/1774176

**Comment by luckyh** [comment]
It can bypass this issue (since it can install `cliff` with the latest version), so we do not have to has a fix.

**Comment by ldoktor** [comment]
Yep, I even sent a fix to upstream, it's merged and new release had been pushed...
